CREATE DATABASE IF NOT EXISTS rinha CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE rinha;

CREATE TABLE IF NOT EXISTS clientes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	limite INT NOT NULL,
	saldo INT NOT NULL DEFAULT 0 
)

CREATE TABLE IF NOT EXISTS transacoes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	idCliente INT NOT NULL,
	valor INT NOT NULL,
	tipo VARCHAR(1) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	dataCriacao DATETIME NOT NULL
)


